version: "3.1"
services:
  nexus3:
    image: sonatype/nexus3
    container_name: nexus3
    ports:
      - "8081:8081"
    volumes:
      - /data/nexus:/nexus-data
    restart: always
    privileged: true