version: '3.3'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    privileged: true
    user: root
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      #将刚刚准备好的defaults.ini直接映射到/usr/share/grafana/conf/defaults.ini路径
      - /data/grafana/config/defaults.ini:/usr/share/grafana/conf/defaults.ini
      #data目录，如果使用了默认的sqlite3数据库，则文件会存在这边
      - /data/grafana/data:/var/lib/grafana
      #log目录，后期会写入log文件
      - /data/grafana/log:/var/log/grafana
  # 添加插件 *注意修改defaults.ini文件：server_url = http://renderer:8081/render
#  renderer:
#    image: grafana/grafana-image-renderer
#    restart: always
#    ports:
#      - 8081:8081
#    container_name: renderer
#    environment:
#      - GF_RENDERER_PLUGIN_TZ=Asia/Shanghai
#      - GF_RENDERER_PLUGIN_IGNORE_HTTPS_ERRORS=true