version: '2.2'
services:
  elasticsearch:
    image: elasticsearch:6.6.2
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    mem_limit: 1024m
    restart: always
    privileged: true
  kibana:
    image: kibana:6.6.2
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    mem_limit: 512m
    restart: always
    privileged: true
  es-head:
    image: mobz/elasticsearch-head:5
    container_name: elasticsearch-head
    privileged: true
    restart: always
    ports:
      - 9100:9100
    links:
      - elasticsearch