version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2-amd64
    container_name: "elasticsearch"
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=tommy-es
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    volumes:
      - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    restart: always
    privileged: true
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    restart: always
    privileged: true
  es-head:
    image: mobz/elasticsearch-head:5
    container_name: elasticsearch-head
    privileged: true
    restart: always
    ports:
      - 9100:9100