version: '2'
services:
  redis:
    image: redis:6.0
    restart: always
    container_name: redis
    command: redis-server --requirepass root
    ports:
      - "6379:6379"
    environment:
      # 设置环境变量 时区上海 编码UTF-8
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes:
      - ./conf/redis.conf:/redis.conf:rw
      - /data/redis/data:/data:rw
    privileged: true