version: '2'
services:
  redis:
    image: redis:6.0
    container_name: redis
    command: redis-server --requirepass root
    ports:
      - "6379:6379"
    volumes:
      - /data/redis:/data
    privileged: true